https://www.hackerrank.com/challenges/np-shape-reshape/problem

In [21]:
s='1 2 3 4 5 6 7 8 9'
import numpy

arr = numpy.array([int(i) for i in s.split()])
arr=arr.reshape([3,3])
print(arr)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
